#!/usr/bin/env bash
# Install the shared Quadlet units (network, volumes) and the orchestrator
# container unit into the Podman Quadlet directory, then reload systemd so the
# Podman Quadlet generator turns them into services.
#
# Per-service units (postgres, rabbitmq, director, text-router, gateway, game
# servers, autoscaler) are written by their own start scripts because they embed
# resolved runtime values and secrets. This script handles only the foundational
# units plus the orchestrator.
set -euo pipefail

cd "$(dirname "$0")/../.."

source runtime/scripts/engine.sh

require_quadlet_privileges || exit 1

REPO_DIR="$(pwd)"

mkdir -p "$DUNE_QUADLET_DIR"

# The orchestrator bind-mounts <repo>/work for catalog extraction output. Podman
# requires bind-mount source paths to exist before the container starts.
mkdir -p "${REPO_DIR}/work"

# Install the static, secret-free units (network + volumes) verbatim.
ensure_quadlet_foundation

# Generate the orchestrator container unit. It is built locally as
# dune-orchestrator:dev and talks to the host Podman API socket so it can load
# Funcom image tarballs onto the host engine.
#
# Quadlet's [Container] EnvironmentFile= does not support systemd's "-" optional
# prefix and resolves bare paths relative to the unit directory, so only emit the
# directive (with an absolute path) when the .env file actually exists.
env_file_line=""
if [ -f "${REPO_DIR}/.env" ]; then
  env_file_line="EnvironmentFile=${REPO_DIR}/.env"
fi

quadlet_write dune-orchestrator.container <<EOF
# Generated by runtime/scripts/render-quadlet.sh. Do not edit by hand.
[Unit]
Description=Dune Awakening orchestrator (SteamCMD downloads and image loading)
Wants=podman.socket
After=podman.socket

[Container]
ContainerName=dune-orchestrator
Image=dune-orchestrator:dev
Pull=never
Network=host
Exec=daemon
SecurityLabelDisable=true
Volume=${DUNE_PODMAN_SOCKET}:/run/podman/podman.sock
Volume=dune-server.volume:/srv/dune/server
Volume=dune-steam.volume:/srv/dune/steam
Volume=dune-cache.volume:/srv/dune/cache
Volume=dune-generated.volume:/srv/dune/generated
Volume=${REPO_DIR}/work:/work:z
Environment=DUNE_ROOT=/srv/dune
Environment=DUNE_SERVER_DIR=/srv/dune/server
Environment=DUNE_STEAM_DIR=/srv/dune/steam
Environment=DUNE_GENERATED_DIR=/srv/dune/generated
${env_file_line}

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target
EOF

quadlet_reload

echo "Installed Quadlet units into ${DUNE_QUADLET_DIR}:"
echo "  dune-net.network"
echo "  dune-server.volume dune-steam.volume dune-cache.volume dune-generated.volume dune-postgres-data.volume"
echo "  dune-orchestrator.container"
