#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

[ -f .env ] && . ./.env
[ -f runtime/generated/battlegroup.env ] && . runtime/generated/battlegroup.env

[ -f runtime/generated/image-tags.env ] && . runtime/generated/image-tags.env
source runtime/scripts/runtime-env.sh
source runtime/scripts/image-tags.sh
require_quadlet_privileges || exit 1
WORLD_IMAGE_TAG="$(resolve_world_image_tag)"
IMAGE="registry.funcom.com/funcom/self-hosting/seabass-server-gateway:${WORLD_IMAGE_TAG}"

TOKEN_FILE="runtime/secrets/funcom-token.txt"
RMQ_SECRET_FILE="runtime/secrets/rmq-http-token-auth-secret.txt"
FLS_APIKEY_FILE="runtime/secrets/fls-apikey.txt"

if [ ! -s "$TOKEN_FILE" ]; then
  echo "Missing Funcom token file: $TOKEN_FILE"
  exit 1
fi

if [ ! -s "$RMQ_SECRET_FILE" ]; then
  openssl rand -hex 32 > "$RMQ_SECRET_FILE"
  chmod 600 "$RMQ_SECRET_FILE"
fi

if [ ! -s "$FLS_APIKEY_FILE" ]; then
  openssl rand -hex 16 > "$FLS_APIKEY_FILE"
  chmod 600 "$FLS_APIKEY_FILE"
fi

FUNCOM_TOKEN="$(tr -d '\r\n' < "$TOKEN_FILE")"
RMQ_HTTP_TOKEN_AUTH_SECRET="$(tr -d '\r\n' < "$RMQ_SECRET_FILE")"
FLS_APIKEY="$(tr -d '\r\n' < "$FLS_APIKEY_FILE")"

SERVER_TITLE="$(resolve_server_title)"
SERVER_REGION="$(resolve_server_region)"
SERVER_IP="$(resolve_server_ip)"
BATTLEGROUP_ID="$(resolve_battlegroup_id)"


mkdir -p runtime/server-gateway/config

REPO_DIR="$(pwd)"

dune_systemctl stop dune-server-gateway.service 2>/dev/null || true
engine rm -f dune-server-gateway 2>/dev/null || true

ensure_quadlet_foundation

quadlet_write dune-server-gateway.container <<EOF
# Generated by runtime/scripts/start-server-gateway.sh. Do not edit by hand.
[Unit]
Description=Dune Awakening server gateway

[Container]
ContainerName=dune-server-gateway
Image=${IMAGE}
Pull=never
Network=dune-net.network
Volume=${REPO_DIR}/runtime/server-gateway/config:/etc/app/conf.d:ro,z
Environment="FuncomLiveServices__ServiceAuthToken=${FUNCOM_TOKEN}"
Environment="FuncomLiveServices__RmqTlsEnabled=true"
Environment="FuncomLiveServices__BattlegroupAuthorizationPreset=BattlegroupInternal"
Environment="RMQ_HTTP_TOKEN_AUTH_SECRET=${RMQ_HTTP_TOKEN_AUTH_SECRET}"
Environment="gateway_farm_api_key=${FLS_APIKEY}"
Environment="HOST_DATACENTER_ID=${SERVER_PROVIDER:-dune-docker}"
Environment="HOST_DATACENTER_IP_ADDRESS=${SERVER_IP}"
Environment="BATTLEGROUP=${BATTLEGROUP_ID}"
Environment="BATTLEGROUP_DISPLAY_NAME=${BATTLEGROUP_ID}"
Environment="BATTLEGROUP_TITLE=${SERVER_TITLE}"
Environment="DuneDatabaseInterfacePSQL_DatabaseHost=dune-postgres:5432"
Environment="DuneDatabaseInterfacePSQL_DatabaseName=dune"
Environment="DuneDatabaseInterfacePSQL_DatabaseUser=dune"
Environment="DuneDatabaseInterfacePSQL_DatabasePassword=dune"
Environment="OnlineSubsystem_ServerName=${BATTLEGROUP_ID}"
Environment="gateway_display_name=${SERVER_TITLE}"
Environment="OnlineSubsystem_DatacenterId=${SERVER_REGION}"
PodmanArgs=--env=fls-apikey=${FLS_APIKEY}
Exec=python -m service -c ./service/configs/service.conf --RMQGameHostname=${SERVER_IP} --RMQGamePort=31982 --RMQGameHttpPort=31983

[Service]
Restart=always
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

quadlet_reload
dune_systemctl start dune-server-gateway.service

sleep 12

engine ps --filter "name=dune-server-gateway" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

echo
echo "=== server-gateway logs ==="
engine logs --tail 180 dune-server-gateway
