#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

source runtime/scripts/engine.sh
require_quadlet_privileges || exit 1

CONTAINER_NAME="dune-autoscaler"
IMAGE="dune-orchestrator:dev"
REPO_DIR="$(pwd)"

mkdir -p runtime/generated runtime/logs

if engine ps --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
  echo "Autoscaler already running: $CONTAINER_NAME"
  exit 0
fi

dune_systemctl stop dune-autoscaler.service 2>/dev/null || true
engine rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true

if ! engine ps --format '{{.Names}}' | grep -qx dune-director; then
  echo "Cannot start autoscaler: dune-director is not running."
  exit 1
fi

if ! engine ps --format '{{.Names}}' | grep -qx dune-postgres; then
  echo "Cannot start autoscaler: dune-postgres is not running."
  exit 1
fi

if ! engine image inspect "$IMAGE" >/dev/null 2>&1; then
  echo "Cannot start autoscaler: orchestrator image not found: $IMAGE"
  echo "Build the orchestrator image first (handled by dune init / dune update install)."
  exit 1
fi

echo "Starting autoscaler container..."

ensure_quadlet_foundation

quadlet_write dune-autoscaler.container <<EOF
# Generated by runtime/scripts/start-autoscaler.sh. Do not edit by hand.
[Unit]
Description=Dune Awakening autoscaler
Wants=podman.socket
After=podman.socket

[Container]
ContainerName=dune-autoscaler
Image=dune-orchestrator:dev
Pull=never
Network=host
SecurityLabelDisable=true
Entrypoint=bash
WorkingDir=${REPO_DIR}
Volume=${DUNE_PODMAN_SOCKET}:/run/podman/podman.sock
Volume=${REPO_DIR}:${REPO_DIR}:z
Exec=runtime/scripts/autoscaler.sh

[Service]
Restart=always
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

quadlet_reload
dune_systemctl start dune-autoscaler.service

echo "Autoscaler started: $CONTAINER_NAME"
echo "Logs:"
echo "  dune autoscaler logs"
