#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

[ -f .env ] && . ./.env
[ -f runtime/generated/battlegroup.env ] && . runtime/generated/battlegroup.env

[ -f runtime/generated/image-tags.env ] && . runtime/generated/image-tags.env
source runtime/scripts/runtime-env.sh
source runtime/scripts/image-tags.sh
require_quadlet_privileges || exit 1
WORLD_IMAGE_TAG="$(resolve_world_image_tag)"
IMAGE="registry.funcom.com/funcom/self-hosting/seabass-server-text-router:${WORLD_IMAGE_TAG}"

TOKEN_FILE="runtime/secrets/funcom-token.txt"
RMQ_SECRET_FILE="runtime/secrets/rmq-http-token-auth-secret.txt"

if [ ! -s "$TOKEN_FILE" ]; then
  echo "Missing Funcom token file: $TOKEN_FILE"
  exit 1
fi

if [ ! -s "$RMQ_SECRET_FILE" ]; then
  openssl rand -hex 32 > "$RMQ_SECRET_FILE"
  chmod 600 "$RMQ_SECRET_FILE"
fi

FUNCOM_TOKEN="$(tr -d '\r\n' < "$TOKEN_FILE")"
RMQ_HTTP_TOKEN_AUTH_SECRET="$(tr -d '\r\n' < "$RMQ_SECRET_FILE")"

SERVER_TITLE="$(resolve_server_title)"
SERVER_REGION="$(resolve_server_region)"
SERVER_IP="$(resolve_server_ip)"
BATTLEGROUP_ID="$(resolve_battlegroup_id)"
if [ -n "${DUNE_FAKE_K8S_SERVICEACCOUNT_DIR:-}" ]; then
  FAKE_K8S_SERVICEACCOUNT_DIR="$DUNE_FAKE_K8S_SERVICEACCOUNT_DIR"
else
  FAKE_K8S_SERVICEACCOUNT_DIR="$PWD/runtime/generated/dune-fake-k8s-serviceaccount-text-router"
fi


mkdir -p "$FAKE_K8S_SERVICEACCOUNT_DIR"

cat > "$FAKE_K8S_SERVICEACCOUNT_DIR/namespace" <<'EOF'
funcom-seabass-dune-docker
EOF

cat > "$FAKE_K8S_SERVICEACCOUNT_DIR/token" <<'EOF'
fake-token
EOF

# Intentionally keep this empty for now.
# With this Funcom build, an invalid Kubernetes CA causes IGWO init to fail non-fatally,
# while a valid CA makes the app try to call igwo.local:6443 and crash unless we provide a compatibility API.
: > "$FAKE_K8S_SERVICEACCOUNT_DIR/ca.crt"

chmod -R 755 "$FAKE_K8S_SERVICEACCOUNT_DIR"

REPO_DIR="$(pwd)"

dune_systemctl stop dune-text-router.service 2>/dev/null || true
engine rm -f dune-text-router 2>/dev/null || true

ensure_quadlet_foundation

echo "Waiting for game RabbitMQ TLS listener..."
for i in $(seq 1 60); do
  if engine exec dune-rmq-game rabbitmq-diagnostics -q listeners 2>/dev/null | grep -q "5672.*amqp/ssl"; then
    echo "Game RabbitMQ TLS listener is ready."
    break
  fi
  sleep 2
done

echo "Waiting for game RabbitMQ AMQPS login path..."
for i in $(seq 1 60); do
  if timeout 3 bash -lc 'cat < /dev/null > /dev/tcp/127.0.0.1/31982' 2>/dev/null; then
    echo "Host port 31982 is reachable."
    break
  fi
  sleep 2
done

quadlet_write dune-text-router.container <<EOF
# Generated by runtime/scripts/start-text-router.sh. Do not edit by hand.
[Unit]
Description=Dune Awakening text router (auth/routing)

[Container]
ContainerName=dune-text-router
Image=${IMAGE}
Pull=never
Network=dune-net.network
PublishPort=127.0.0.1:5059:5059/tcp
Volume=${FAKE_K8S_SERVICEACCOUNT_DIR}:/run/secrets/kubernetes.io/serviceaccount:ro,z
Environment="KUBERNETES_SERVICE_HOST=igwo.local"
Environment="KUBERNETES_SERVICE_PORT=6443"
Environment="KUBERNETES_SERVICE_PORT_HTTPS=6443"
Environment="BATTLEGROUP=${BATTLEGROUP_ID}"
Environment="BATTLEGROUP_DISPLAY_NAME=${SERVER_TITLE}"
Environment="BATTLEGROUP_REGION_NAME=${SERVER_REGION}"
Environment="FuncomLiveServices__ServiceAuthToken=${FUNCOM_TOKEN}"
Environment="FuncomLiveServices__RmqTlsEnabled=true"
Environment="RMQ_HTTP_TOKEN_AUTH_SECRET=${RMQ_HTTP_TOKEN_AUTH_SECRET}"
Environment="BATTLEGROUP_LANGUAGE=en-US"
Environment="HOST_DATACENTER_ID=${SERVER_PROVIDER:-dune-docker}"
Environment="HOST_DATACENTER_IP_ADDRESS=${SERVER_IP}"
Environment="ASPNETCORE_URLS=http://0.0.0.0:5059"
Environment="DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false"
Environment="Database_address=dune-postgres:5432"
Environment="Database_name=dune"
Environment="Database_user=dune"
Environment="Database_password=dune"
Exec=--RMQAdminHostname=dune-rmq-admin --RMQAdminPort=5672 --RMQGameHostname=dune-rmq-game --RMQGamePort=5672

[Service]
Restart=always
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

quadlet_reload
dune_systemctl start dune-text-router.service

sleep 8

engine ps --filter "name=dune-text-router" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

echo
echo "=== text-router logs ==="
engine logs --tail 120 dune-text-router
